apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-azure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-azure
  template:
    metadata:
      labels:
        app: hello-azure
    spec:
      containers:
      - name: hello-azure
        image: yomiping/hello-azure-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-azure-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    app: hello-azure

